# Generated by Django 3.2.4 on 2021-07-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210710_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order'},
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.CharField(max_length=1000),
        ),
    ]
