# Generated by Django 3.2.4 on 2021-07-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='itemsp',
        ),
    ]
